### ISSUE TITLE
Destroy effect doesn't work on bot messages + No error messages

### ISSUE THREAD

**Issue by MxtrGaming** [DiSkyOrg/DiSky#56] opened 2022-06-23 13:53 UTC
Hi i need a little help.
whatever i do i can't delete any messages that bot send, tested on (DiSky 4.0 beta 4 and DiSky release 4.0.1)

My code (no errors in console):
![image](https://user-images.githubusercontent.com/44116535/175313639-39e44801-c79a-45d7-88f8-27585930476d.png)

I don't even know if im doing something wrong, because even if i type "sgasgas" for example after "discord command"/"on discord command" event, skript doesn't show any errors.

![image](https://user-images.githubusercontent.com/44116535/175314504-699e4ef2-cbcd-4dec-9862-3dce3aefe0e7.png)

![image](https://user-images.githubusercontent.com/44116535/175318178-6ce808ff-28aa-4371-88b9-89648be726cf.png)

**Comment by SkyCraft78** [comment] 2022-06-23 16:24
This happens sometimes with a specific Server's or Skript's state (aka features on Skript or the server has changed from their original values, therefore it makes an unexpected behavior.) I sent a message over Skript's developer channel to know how could I fix it, and if it's even because of DiSky, but no answer was successful and we still don't know why this happens.

**Comment by SkyCraft78** [comment] 2022-06-26 20:08
I finally found a fix for this.
The way to load the scope's sections (like `trigger:`) is different between the discord command scope & the defined bot scope.
Indeed, discord commands use the Vixio's loading way (Try/Catching retaining logs) while the new scope system uses the plain Skript system (as if we load an actual script).
I replaced the `trigger` loading code of the discord command with the new scope code.

**Closed by SkyCraft78** 2022-06-26 20:08 UTC
Labels: state - won't fix, type - internal
