### ISSUE TITLE
cant set components

### ISSUE THREAD

**Issue by DampfWaffel** [DiSkyOrg/DiSky#82] opened 2022-08-28 08:00 UTC
The Error:
```
[09:56:06 INFO]: [Skript] Reloading modula.sk...
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! [Skript] Severe Error:
[09:56:06 ERROR]: #!#! Could not load modula.sk
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Something went horribly wrong with Skript.
[09:56:06 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:56:06 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:56:06 ERROR]: #!#! Here is full list of them:
[09:56:06 ERROR]: #!#! skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) DiSky v4.4.0 SkImage v1.8 skript-yaml v1.4 SkriptDocsGenerator v1.2.1 (https://github.com/Skylyxx/SkriptDocsGenerator) skript-db v1.3.4
[09:56:06 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:56:06 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:56:06 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:56:06 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:56:06 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:56:06 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Stack trace:
[09:56:06 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.util.Utils.getSuperType(Utils.java:622)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Variable.<init>(Variable.java:102)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Variable.getConvertedExpression(Variable.java:290)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Variable.getConvertedExpression(Variable.java:69)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.effects.EffChange.init(EffChange.java:212)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:255)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:177)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.Statement.parse(Statement.java:60)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1114)
[09:56:06 ERROR]: #!#!     at skript-reflect-2.3.jar//com.btk5h.skriptmirror.util.SkriptUtil.getItemsFromNode(SkriptUtil.java:88)
[09:56:06 ERROR]: #!#!     at skript-reflect-2.3.jar//com.btk5h.skriptmirror.skript.custom.expression.CustomExpressionSection.init(CustomExpressionSection.java:267)
[09:56:06 ERROR]: #!#!     at skript-reflect-2.3.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:214)
[09:56:06 ERROR]: #!#!     at skript-reflect-2.3.jar//com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:182)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1054)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1020)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:1061)
[09:56:06 ERROR]: #!#!     at Skript-2.6.3.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:171)
[09:56:06 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:56:06 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[09:56:06 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[09:56:06 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869)
[09:56:06 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.be(DedicatedServer.java:549)
[09:56:06 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:523)
[09:56:06 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[09:56:06 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[09:56:06 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[09:56:06 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Version Information:
[09:56:06 ERROR]: #!#!   Skript: 2.6.3 (latest)
[09:56:06 ERROR]: #!#!     Flavor: skriptlang-github
[09:56:06 ERROR]: #!#!     Date: 00:55:22.847925631
[09:56:06 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[09:56:06 ERROR]: #!#!   Minecraft: 1.18.2
[09:56:06 ERROR]: #!#!   Java: 17.0.4 (OpenJDK 64-Bit Server VM 17.0.4+8)
[09:56:06 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Server platform: Paper
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Current node: set components row of {_m} to {_row::*} (modula.sk, line 26)
[09:56:06 ERROR]: #!#! Current item: null
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Thread: Server thread
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! Language: english
[09:56:06 ERROR]: #!#! Link parse mode: DISABLED
[09:56:06 ERROR]: #!#!
[09:56:06 ERROR]: #!#! End of Error.
[09:56:06 ERROR]: #!#!
[09:56:06 INFO]: [Skript] Successfully reloaded modula.sk. (10ms)
```

The Code:
```
expression clean[er] modal[a] with [id] %string% [and] (name|named) %string% with [content] %objects%:
	get:
		set {_m} to new modal with id expr-1 named expr-2
		set {_get::*} to expr-3
		loop {_get::*}:
			set {_getter::*} to split "%loop-value%" at "@@"
			loop {_getter::*}:
				set {_r} to {_r}+1
				if {_r} > 5:
					message "&4[&c!&4] &cModal only support 5 Inputs! (%{_r}%)" to console
					continue 
				add {_r} to {_toLoad::*}
				set {_row::%{_r}%} to new components row
				
				set {_input::*} to split "%loop-value-2%" at "||"
				
				set {_input::1} to lower case {_input::1}
				replace all " " with "_" in {_input::1}
				set {_temp} to new text input with id "%{_input::1}%" named "%{_input::2}%"
				set placeholder of {_temp} to "%{_input::3}%"
				set minimum range of {_temp} to first element out of (split {_input::4} at "-") parsed as number
				set maximum range of {_temp} to last element out of (split {_input::4} at "-") parsed as number
				set required state of {_temp} to {_input::5} parsed as boolean
				add {_temp} to components of {_row::%{_r}%} 
				
		set components row of {_m} to {_row::*}
		return {_m}
```
Server:
```
[09:59:57 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:59:57 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[09:59:57 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[09:59:57 INFO]: [Skript] Server Version: git-Purpur-1632 (MC: 1.18.2)
[09:59:57 INFO]: [Skript] Skript Version: 2.6.3
[09:59:57 INFO]: [Skript] Installed Skript Addons:
[09:59:57 INFO]: [Skript]  - SkImage v1.8
[09:59:57 INFO]: [Skript]  - DiSky v4.4.0
[09:59:57 INFO]: [Skript]  - skript-yaml v1.4
[09:59:57 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[09:59:57 INFO]: [Skript]  - skript-db v1.3.4
[09:59:57 INFO]: [Skript] Installed dependencies:
[09:59:57 INFO]: [Skript]  - Vault v1.7.3-b131
```
was this changed in 4.4.0 aswell?

**Comment by SkyCraft78** [comment] 2022-08-28 13:07
This seems to be caused by skript-reflect's code. No DiSky classes are included in the stack trace.
I'll take a look at the expression and come back if I find anything good.

**Comment by SkyCraft78** [comment] 2022-08-28 15:27
I am able to make modal work normally, maybe it's through using custom syntax via skript-reflect that causes the error?
Don't seems related to DiSky anyways, for now, closing this. Feel free to re-open it once you have more information.

**Closed by SkyCraft78** 2022-08-28 15:27 UTC
Labels: type - bug, state - won't fix

**Comment by DampfWaffel** [comment] 2022-08-28 18:50
yes. i had to rewrite some parts. but now it works again.
btw. how can i update snippets in discord? or do i have to upload them again?

removed the `set components row of {_m} to {_row::*}` and just added the new compents row to the modal with `add {_row::%{_r}%} to the rows of {_m}`
