### ISSUE TITLE
DiSky crashing on ~1GB RAM servers

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#96] opened 2022-11-08 20:00 UTC
Hello.
So I saw people complaining about DiSky (the latest versions) crashing their Minehut free plan servers (those have 1GB ram, this issue could also happen on other hosts with 1GB), so I decided to open a bug report.
Pretty much, when you reload your Discord skript with the `define a new bot named "NAME"` scope, your poor server will either freeze or fuck itself in the ass (crash).
A solution I have is to use an older version of DiSky such as 4.0-beta4 (which works flawlessly and should not cause havoc to your poor server), or if the people really care about the new features, wait until you get a fix.

**Anyone who has the bug may comment here to show Sky that it's not a "you" issue.**

**Comment by soudeir** [comment] 2022-11-08 20:22
thing is it worked fine few days ago, and fucked up for no reason

**Comment by Devc2** [comment] 2022-11-08 20:38
Yea same

**Comment by SkyCraft78** [comment] 2022-11-08 21:54
DiSky run everything relayed to itself (aka discord code) asynchronously since V3. The only way for it to crash the server is because the side-thread used to executes Discord things is being overflowed by request.
The best thing I can ask is the timings of your server (search for a plugin like this, or if you have paper there's a command for it) and send them here, I'll be glad to take a look and fix a possible weakness in the DiSky's performance

**Comment by Devc2** [comment] 2022-11-09 04:40
> DiSky run everything relayed to itself (aka discord code) asynchronously since V3. The only way for it to crash the server is because the side-thread used to executes Discord things is being overflowed by request. The best thing I can ask is the timings of your server (search for a plugin like this, or if you have paper there's a command for it) and send them here, I'll be glad to take a look and fix a possible weakness in the DiSky's performance
right now if you want to test your skripts move to another host like server.pro where you can upload your own files

**Comment by soudeir** [comment] 2022-11-09 13:23
> 

how to use the timings, cuz when i reload the skript, the server crashes instantly after i run the reload command and then i cant take the timings, and when the server turns on the timings will reset

**Comment by CerialPvP** [comment] 2022-11-09 14:42
> how to use the timings, cuz when i reload the skript, the server crashes instantly after i run the reload command and then i cant take the timings, and when the server turns on the timings will reset

wait like 2 minutes without reloading, then do /timings get or whatever the command is

**Comment by DampfWaffel** [comment] 2022-11-09 21:54
Hello, I am currently only able to repuduce this behavior on minehut.

[log from local pc.log](https://github.com/DiSkyOrg/DiSky/files/9975411/log.from.local.pc.log)
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8)
OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode, sharing)
```


Even on my local computer with the flag `-Xmx1024M` the server does not crash. so i do not think it is a disky error.
[crash log from minehut.log](https://github.com/DiSkyOrg/DiSky/files/9975406/crash.log.from.minehut.log)

Timings but without the crash because the server is frezzing and can not respond so he did not give me a link: https://timings.aikar.co/dev/?id=81707deba4b849a9b968e228c584a1a6

Have you tried to reach Minehut support? (not forum!)

**Comment by SkyCraft78** [comment] 2022-11-10 18:33
I am also unable to reproduce this on a 512Mb server running Java 16 with Paper 1.19.
I'm closing this for now, you should go ask on MineHut's forum for more information about that.

**Closed by SkyCraft78** 2022-11-10 18:33 UTC
Labels: type - bug, type - invalid, state - won't fix

**Comment by honkling** [comment] 2022-11-12 02:36
> The only way for it to crash the server is because the side-thread used to executes Discord things is being overflowed by request.
Not a DiSky issue, in fact a JDA issue exclusive to Minehut containers, however it appears that logging in is not asynchronous in DiSky. Using JDA with skript-reflect crashes just like DiSky does, but not when I log in on a new thread.

Specifically, it appears that JDA hangs the main thread when attempting to check if the provided token is valid. This is done with a CompletableFuture, and JDA just waits for the response to come from the future, but the response never arrives, thus the hanging.

Might want to look into making V3 a bit more asynchronous than it apparently is.
