### ISSUE TITLE
Disky runs before Skript

### ISSUE THREAD

**Issue by TechnicalityMods** [DiSkyOrg/DiSky#132] opened 2023-05-01 12:35 UTC
Disky decides to start up before skript which causes it to disable itself since skript wasn't enabled yet

**Comment by TechnicalityMods** [comment] 2023-05-01 12:46
Error Message:
[12:45:50 ERROR]: Error occurred while enabling DiSky v4.11.1 (Is it up to date?)
java.lang.IllegalStateException: Skript was never loaded
        at ch.njol.skript.Skript.isAcceptRegistrations(Skript.java:1260) ~[DiSky 4.11.1.jar:?]
        at ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1265) ~[DiSky 4.11.1.jar:?]
        at ch.njol.skript.Skript.registerEvent(Skript.java:1467) ~[DiSky 4.11.1.jar:?]
        at ch.njol.skript.Skript.registerEvent(Skript.java:1454) ~[DiSky 4.11.1.jar:?]
        at info.itsthesky.disky.structures.scope.BotScope.register(BotScope.java:77) ~[DiSky 4.11.1.jar:?]
        at info.itsthesky.disky.structures.scope.ScopeLoader.load(ScopeLoader.java:18) ~[DiSky 4.11.1.jar:?]
        at info.itsthesky.disky.DiSky.onEnable(DiSky.java:75) ~[DiSky 4.11.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at me.Coderforlife.Disable.Me.enablePlugin(Me.java:133) ~[DisableMe1.3.jar:?]
        at me.Coderforlife.Disable.Me.onCommand(Me.java:70) ~[DisableMe1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-215]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-215]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-215]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-215]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CerialPvP** [comment] 2023-05-01 17:55
what version of disky do you have? if its an old version update, but if for some reason you can't then you can download disky's source code, and then change the plugin.yml to depend on skript instead of soft-depend (idk how it is, but do it)

**Comment by ItsTheSky** [comment] 2023-05-05 10:31
This is caused by the new 2.7 updates. I'll dig for more info on my side and keep you updated!

**Comment by TheJappie27** [comment] 2023-05-05 10:36
I have the same error, although console says that skript is loaded succesfully before DiSky. Should I open a new issue or do you think it's the same as this one?

**Comment by ItsTheSky** [comment] 2023-05-05 10:38
Nah it's the same one, DiSky seems to not detect Skript since the 2.7 version. I asked SkriptLang's team to know what's happening there

**Comment by ItsTheSky** [comment] 2023-05-15 18:46
Still waiting for an answer in skUnity discord

**Comment by ItsTheSky** [comment] 2023-08-07 17:03
Should be fixed in 4.12.0. I just tried with Skript 2.7-beta3 and it loads fine.

**Closed by ItsTheSky** 2023-08-07 17:03 UTC
Labels: type - internal, state - will fix/add
